// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://popsulpfnozhkuiayetd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcHN1bHBmbm96aGt1aWF5ZXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDg5OTksImV4cCI6MjA2Mzk4NDk5OX0.p1nUonurqUCiAG75Os5Ovr2tZL62XyLbtBXeIshZ27M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);